# Generated by Django 5.2 on 2025-04-16 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_loginattempt'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='email_confirmation_sent_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='email_confirmation_token',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
