# Generated by Django 5.2 on 2025-04-16 20:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_userprofile_email_confirmed'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('password_hash', models.CharField(blank=True, max_length=128, null=True)),
                ('can_download', models.BooleanField(default=False)),
                ('max_selections', models.PositiveIntegerField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('welcome_message', models.TextField(blank=True)),
                ('notify_on_selection', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_links', to='api.album')),
            ],
        ),
        migrations.CreateModel(
            name='ClientSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('access_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selections', to='api.accesslink')),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.photo')),
            ],
            options={
                'unique_together': {('access_link', 'photo')},
            },
        ),
    ]
