# Generated by Django 5.2 on 2025-04-16 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_accesslink_clientselection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accesslink',
            name='password_hash',
        ),
        migrations.AddField(
            model_name='accesslink',
            name='password',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
