# Generated by Django 5.2 on 2025-04-17 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_remove_accesslink_password_hash_accesslink_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesslink',
            name='password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
