# Generated by Django 5.2 on 2025-04-17 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_album_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesslink',
            name='client_name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
